main: fr.pederobien.minecraft.mumble.server.MumbleServerPlugin
name: minecraft-mumble-server
version: 1.0-SNAPSHOT
api-version: 1.16

commands:
  mumble:
    description: This command is used to configure a mumble server.
    permission: MumblePlugin.permission